### ISSUE TITLE
The package can't split "helloworld".

### ISSUE THREAD

**Issue by yi03** [keredson/wordninja#2]
The package is wonderful, but I find it can't split "helloworld". I guess it may be a bug, so I say it here.

**Comment by cstrike** [comment]
'quicksort' either

**Comment by adrianog** [comment]
It is trained on wikipedia, so probably helloworld is part of the vocabulary.

**Comment by keredson** [comment]
correct:
```
$ zcat wordninja/wordninja_words.txt.gz | grep -n ^helloworld$ 
79530:helloworld
```
