### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by ghost** [keredson/wordninja#20]
Hi I don't understand how could add an Italian dictionary to process the word in the right way. Do you explain me how I could, please? Thank you for you're support and you're patience, and I apologise for my stupid question

**Comment by ghost** [comment]
I'm done guys. Had a few problems. with Italian language, but i solved it

**Comment by marctorsoc** [comment]
@ghost where did you get from the data for Italian language ?

**Comment by marctorsoc** [comment]
@keredson is there any public repo or elsewhere with data for different languages?

**Comment by marctorsoc** [comment]
I see! is it this? https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists. Maybe you could add to the README?
