### ISSUE TITLE
Splitting iam

### ISSUE THREAD

**Issue by adrianog** [keredson/wordninja#3]
So "Iam" doesn't work (splits into ['I', 'a', 'm'] - that seems to be the case for any capitalised word).

And "iam", stays "iam".

**Comment by keredson** [comment]
weird.  there's a whole https://en.wikipedia.org/wiki/IAM

**Comment by keredson** [comment]
and prob. since wikipedia is always written in the third person, "i am" is prob. pretty infrequent.

**Comment by SpongebobSquamirez** [comment]
Yeah, capitalized words always split like that. Seems like a bug, or something that should be documented.

**Comment by SpongebobSquamirez** [comment]
Looks like this was resolved by a commit by the maintainer.
