### ISSUE TITLE
Read other language dictionaries

### ISSUE THREAD

**Issue by mjcortejo** [keredson/wordninja#8]
Hello,

I would like to suggest an enhancement to allow other language dictionaries to be fed in wordninja.
The parameter right now is configured to use wordninja_words.txt.gz.

Thank you!

**Comment by jbingel** [comment]
Yes please! In general, it would be great if it was easier to provide custom dictionaries. I suppose the most convenient way (for the user...) would be if one could specify a dictionary file at runtime?

**Comment by datalee** [comment]
> could specify a dictionary file at runtime?

+1

**Comment by keredson** [comment]
done!  see Custom Language Models in readme.
